spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/strahovka
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  flyway:
    enabled: false
  sql:
    init:
      mode: never
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB

server:
  port: 8081
  tomcat:
    max-threads: 200
    min-spare-threads: 10

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.web.access: DEBUG
    org.springframework.security.web.context: DEBUG
    org.springframework.security.web.authentication: DEBUG
    org.springframework.security.authentication: DEBUG
    org.springframework.security.core.userdetails: DEBUG
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    com.strahovka: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 7

jwt:
  secret: "strahovka_super_secret_key_for_jwt_signing_that_is_at_least_64_bytes_long_and_very_secure_2024_production"
  expiration: 86400000 # 24 hours in milliseconds

cors:
  allowed-origins: http://localhost:3000,http://localhost:3001,http://localhost:3002 